Feat/requirement one
Bootcamp-Time7/projeto-integrador pull request #3
Opened 2022-08-05 14:08 UTC by monicaschneimercadolivre

Adicionando requisito um na branch develop

2022-08-05 17:29 UTC, amandaamabili requested changes
Alteração 1 =>  O pom.xml precisa estar dentro do git ignore. Para não ser excluído novamente em cada versão. A não ser que, você tenha colocado uma nova dependência.
Alteração 2 =>  O src/main/resources/application.properties precisa ignorar também sua versão e aceitar no merge a versão que está em develop.

2022-08-05 17:29 UTC, amandaamabili commented on pom.xml
> +        <dependency>
isso já está em dev

2022-08-05 17:29 UTC, amandaamabili commented on src/main/java/com/desafiofinal/praticafinal/modelDto/BatchStockDto.java
> +   /* public BatchStock convertBatchStockDtoToBatchStock (BatchStockDto batchStockDto){
Esses comentários irão ser reutilizados?

2022-08-05 17:29 UTC, amandaamabili commented on src/main/resources/application.properties
> +# 1 - usuário do BD
Não enviar esse arquivo para develop. Pois já está correto em dev.

2022-08-08 13:17 UTC, nCalderari approved these changes

2022-08-08 13:18 UTC, amandaamabili approved these changes

2022-08-08 13:18 UTC, nCalderari approved these changes

2022-08-08 13:21 UTC, merged